#!/usr/bin/env bash
# Install + run Parakeet TDT STT for Linux.
#
# The Tauri app auto-spawns: binaries/parakeet/parakeet-server-x86_64-unknown-linux-gnu
# This script (1) prepares the Python env and (2) writes/refreshes that launcher.
#
# Usage:
#   bash scripts/run-parakeet-linux.sh            # install + run in foreground
#   bash scripts/run-parakeet-linux.sh --install   # install/refresh launcher only
#   deno task parakeet:linux
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STT_DIR="${PARAKEET_DIR:-$ROOT/.cache/parakeet-tdt}"
PORT="${PARAKEET_PORT:-5092}"
LAUNCHER_DIR="$ROOT/binaries/parakeet"
LAUNCHER="$LAUNCHER_DIR/parakeet-server-x86_64-unknown-linux-gnu"
MODE="${1:-}"

if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "error: ffmpeg required (pacman -S ffmpeg)" >&2
  exit 1
fi
if ! command -v uv >/dev/null 2>&1; then
  echo "error: uv required (https://github.com/astral-sh/uv)" >&2
  exit 1
fi

mkdir -p "$(dirname "$STT_DIR")" "$LAUNCHER_DIR"
if [[ ! -d "$STT_DIR/.git" ]]; then
  echo "Cloning Parakeet FastAPI server…"
  git clone --depth 1 \
    https://github.com/groxaxo/parakeet-tdt-0.6b-v3-fastapi-openai \
    "$STT_DIR"
fi

cd "$STT_DIR"

PY="${PARAKEET_PYTHON:-3.12}"
if [[ ! -d .venv ]]; then
  echo "Creating venv with Python $PY…"
  uv venv --python "$PY" .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate

MARKER=".venv/.cpu_deps_ok"
if [[ ! -f "$MARKER" ]]; then
  echo "Installing CPU deps (torch CPU wheel — avoids multi-GB CUDA packs)…"
  uv pip install --index-url https://download.pytorch.org/whl/cpu \
    "torch" "torchaudio"
  REQ_CPU="$(mktemp)"
  grep -vE '^(onnxruntime-gpu|silero-vad)' requirements.txt > "$REQ_CPU" || true
  echo "onnxruntime==1.23.2" >> "$REQ_CPU"
  echo "silero-vad>=6.0.0" >> "$REQ_CPU"
  uv pip install -r "$REQ_CPU"
  rm -f "$REQ_CPU"
  touch "$MARKER"
  echo "Deps ready."
else
  echo "Deps already installed (.venv)."
fi

mkdir -p "$STT_DIR/models"

# ── Write launcher the Tauri sidecar spawn will exec ──────────────────────────
# Important: launcher ends with `exec python …` so the tracked PID is the
# Python process (killed cleanly on app exit).
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/run-parakeet-linux.sh — do not edit by hand.
set -euo pipefail
STT_DIR="$STT_DIR"
cd "\$STT_DIR"
# shellcheck disable=SC1091
source "\$STT_DIR/.venv/bin/activate"
export PARAKEET_USE_GPU=false
export PARAKEET_DEFAULT_MODEL="\${PARAKEET_DEFAULT_MODEL:-parakeet-tdt-0.6b-v3}"
export PARAKEET_BATCHED=0
export HF_HOME="\$STT_DIR/models"
export HF_HUB_CACHE="\$STT_DIR/models"
export HOST=0.0.0.0
export PORT=${PORT}
if [[ -f server.py ]]; then
  exec python server.py
fi
if [[ -f app.py ]]; then
  exec python app.py
fi
echo "error: no server.py/app.py in \$STT_DIR" >&2
exit 1
EOF
chmod +x "$LAUNCHER"
echo "Launcher ready: $LAUNCHER"

if [[ "$MODE" == "--install" || "$MODE" == "install" ]]; then
  echo "Parakeet install complete (sidecar will start with the app)."
  exit 0
fi

# Foreground run (manual / deno task)
export PARAKEET_USE_GPU=false
export PARAKEET_DEFAULT_MODEL="${PARAKEET_DEFAULT_MODEL:-parakeet-tdt-0.6b-v3}"
export PARAKEET_BATCHED=0
export HF_HOME="$STT_DIR/models"
export HF_HUB_CACHE="$STT_DIR/models"

echo
echo "Starting Parakeet on http://127.0.0.1:${PORT}"
echo "Health: http://127.0.0.1:${PORT}/healthz"
echo

exec "$LAUNCHER"
